# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "boa-home-task-EL"
client_id = "10839df1bf5f3fb98a53a081e7251bcb"
application_url = "https://draws-repository-earning-terrorism.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://draws-repository-earning-terrorism.trycloudflare.com/auth/callback",
  "https://draws-repository-earning-terrorism.trycloudflare.com/auth/shopify/callback",
  "https://draws-repository-earning-terrorism.trycloudflare.com/api/auth/callback",
  "https://draws-repository-earning-terrorism.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "home-assignment-50.myshopify.com"
